# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Crypto' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Crypto
  pod 'Firebase/Auth'
  
  target 'CryptoTests' do
    inherit! :search_paths
    pod 'Firebase/Auth'
  end

  target 'CryptoUITests' do
    pod 'Firebase/Auth'
  end

end
